//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Windows.AddEditColorWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddEditColorWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddEditColorWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Windows.AddEditColorWindow.AddEditColorWindowResour" +
                            "ces", typeof(AddEditColorWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDeleteContent {
            get {
                return ResourceManager.GetString("ButtonDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha :.
        /// </summary>
        internal static string LabelAlphaChannel {
            get {
                return ResourceManager.GetString("LabelAlphaChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue :.
        /// </summary>
        internal static string LabelBlueChannel {
            get {
                return ResourceManager.GetString("LabelBlueChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green :.
        /// </summary>
        internal static string LabelGreenChannel {
            get {
                return ResourceManager.GetString("LabelGreenChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal code :.
        /// </summary>
        internal static string LabelHexadecimalCode {
            get {
                return ResourceManager.GetString("LabelHexadecimalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue :.
        /// </summary>
        internal static string LabelHueChannel {
            get {
                return ResourceManager.GetString("LabelHueChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview :.
        /// </summary>
        internal static string LabelPreview {
            get {
                return ResourceManager.GetString("LabelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red :.
        /// </summary>
        internal static string LabelRedChannel {
            get {
                return ResourceManager.GetString("LabelRedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation :.
        /// </summary>
        internal static string LabelSaturationChannel {
            get {
                return ResourceManager.GetString("LabelSaturationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value :.
        /// </summary>
        internal static string LabelValueChannel {
            get {
                return ResourceManager.GetString("LabelValueChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add duplicate color hexadecimal code, existing color name is &quot;{0}&quot;.
        /// </summary>
        internal static string MessageBoxCannotAddDuplicateColorHexError {
            get {
                return ResourceManager.GetString("MessageBoxCannotAddDuplicateColorHexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color name already exists.
        /// </summary>
        internal static string MessageBoxCannotAddDuplicateColorNameError {
            get {
                return ResourceManager.GetString("MessageBoxCannotAddDuplicateColorNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add empty color hex code.
        /// </summary>
        internal static string MessageBoxCannotAddEmptyColorHexError {
            get {
                return ResourceManager.GetString("MessageBoxCannotAddEmptyColorHexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add empty color name.
        /// </summary>
        internal static string MessageBoxCannotAddEmptyColorNameError {
            get {
                return ResourceManager.GetString("MessageBoxCannotAddEmptyColorNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color name :.
        /// </summary>
        internal static string TextBoxColorName {
            get {
                return ResourceManager.GetString("TextBoxColorName", resourceCulture);
            }
        }
    }
}
