//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.DetailedRecordContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailedRecordContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedRecordContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.DetailedRecordContentPage.Deta" +
                            "iledRecordContentPageResources", typeof(DetailedRecordContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelUpdateText {
            get {
                return ResourceManager.GetString("ButtonCancelUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refocus.
        /// </summary>
        internal static string ButtonRefocusText {
            get {
                return ResourceManager.GetString("ButtonRefocusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ButtonUpdateText {
            get {
                return ResourceManager.GetString("ButtonUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added on.
        /// </summary>
        internal static string LabelTextAddedOn {
            get {
                return ResourceManager.GetString("LabelTextAddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed on.
        /// </summary>
        internal static string LabelTextPointedOn {
            get {
                return ResourceManager.GetString("LabelTextPointedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating the history. Please try again.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made to this record ?.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedMessage {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedNoButton {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedTitle {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedYesButton {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        internal static string PlaceholderTextCity {
            get {
                return ResourceManager.GetString("PlaceholderTextCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string PlaceholderTextCountry {
            get {
                return ResourceManager.GetString("PlaceholderTextCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place :.
        /// </summary>
        internal static string PlaceholderTextPlace {
            get {
                return ResourceManager.GetString("PlaceholderTextPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed operation.
        /// </summary>
        internal static string PointedOperation {
            get {
                return ResourceManager.GetString("PointedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in progress.
        /// </summary>
        internal static string TitleIsDirty {
            get {
                return ResourceManager.GetString("TitleIsDirty", resourceCulture);
            }
        }
    }
}
