//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.AddEditAccountContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddEditAccountContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddEditAccountContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.AddEditAccountContentPage.AddE" +
                            "ditAccountContentPageResources", typeof(AddEditAccountContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidText {
            get {
                return ResourceManager.GetString("ButtonValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type :.
        /// </summary>
        internal static string LabelTextTitleAccountType {
            get {
                return ResourceManager.GetString("LabelTextTitleAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency :.
        /// </summary>
        internal static string LabelTextTitleCurrency {
            get {
                return ResourceManager.GetString("LabelTextTitleCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type cannot be null.
        /// </summary>
        internal static string MessageBoxButtonValidationAccountTypeFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationAccountTypeFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account currency type cannot be blank.
        /// </summary>
        internal static string MessageBoxButtonValidationCurrencyFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationCurrencyFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account name cannot be empty.
        /// </summary>
        internal static string MessageBoxButtonValidationNameError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account, please retry.
        /// </summary>
        internal static string MessageBoxDeleteAccountErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxDeleteAccountErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxDeleteAccountErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?{0}All associated items will also be deleted. Please note, this may take more or less time depending on the amount of data to be deleted.
        /// </summary>
        internal static string MessageBoxDeleteAccountQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxDeleteAccountQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBoxDeleteAccountQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxDeleteAccountQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully deleted.
        /// </summary>
        internal static string MessageBoxDeleteAccountSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxDeleteAccountSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxDeleteAccountSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating. Please try again.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was added or edited successfully.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxOnBackCommandPressedSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxOnBackCommandPressedSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxValidAccountErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidAccountErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValidAccountErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidAccountErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name :.
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
    }
}
