//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.AccountTypeSummaryContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountTypeSummaryContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountTypeSummaryContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.AccountTypeSummaryContentPage." +
                            "AccountTypeSummaryContentPageResources", typeof(AccountTypeSummaryContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidText {
            get {
                return ResourceManager.GetString("ButtonValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding account type, please retry.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeErrorMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeErrorOkButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeErrorTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add &quot;{0}&quot; as a new account type ?.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeQuestionMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeQuestionNoButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account type ?.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeQuestionTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeQuestionYesButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type was successfully added.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeSuccessMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeSuccessOkButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MesageBoxAddNewAccountTypeSuccessTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewAccountTypeSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type already exist.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorAlreadyExistOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorAlreadyExistTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type can&apos;t be empty.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorEmptyMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorEmptyOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValidateAccountTypeErrorEmptyTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account type :.
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
    }
}
