//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Windows.RecurrentAddWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecurrentAddWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecurrentAddWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Windows.RecurrentAddWindow.RecurrentAddWindowResour" +
                            "ces", typeof(RecurrentAddWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string DataGridCheckBoxColumnRecursiveToAddHeader {
            get {
                return ResourceManager.GetString("DataGridCheckBoxColumnRecursiveToAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd hh:mm.
        /// </summary>
        internal static string DataGridDateFormatString {
            get {
                return ResourceManager.GetString("DataGridDateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DataGridTemplateColumnCategoryHeader {
            get {
                return ResourceManager.GetString("DataGridTemplateColumnCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DataGridTemplateColumnValueHeader {
            get {
                return ResourceManager.GetString("DataGridTemplateColumnValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string DataGridTextColumnAccountHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DataGridTextColumnDescriptionHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string DataGridTextColumnModePaymentHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnModePaymentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next due date.
        /// </summary>
        internal static string DataGridTextColumnNextDueDateHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnNextDueDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string DataGridTextColumnNoteHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnNoteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string DataGridTextColumnPlaceHeader {
            get {
                return ResourceManager.GetString("DataGridTextColumnPlaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more recurring expenses to add.
        ///Please disable the ones you don&apos;t want to add or cancel to not add any..
        /// </summary>
        internal static string TextBlockAddRecurrenceNeeded {
            get {
                return ResourceManager.GetString("TextBlockAddRecurrenceNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recurring expenses.
        /// </summary>
        internal static string TitleWindow {
            get {
                return ResourceManager.GetString("TitleWindow", resourceCulture);
            }
        }
    }
}
