//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.AddEditAccount {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddEditAccountResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AddEditAccountResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.AddEditAccount.AddEditAccountResources", typeof(AddEditAccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonValidText {
            get {
                return ResourceManager.GetString("ButtonValidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting account and all related transactions.
        /// </summary>
        public static string CustomPopupActivityIndicatorDeleteAccount {
            get {
                return ResourceManager.GetString("CustomPopupActivityIndicatorDeleteAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account type :.
        /// </summary>
        public static string LabelTextTitleAccountType {
            get {
                return ResourceManager.GetString("LabelTextTitleAccountType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency :.
        /// </summary>
        public static string LabelTextTitleCurrency {
            get {
                return ResourceManager.GetString("LabelTextTitleCurrency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxAddAccountError {
            get {
                return ResourceManager.GetString("MessageBoxAddAccountError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account was successfully added.
        /// </summary>
        public static string MessageBoxAddAccountSuccess {
            get {
                return ResourceManager.GetString("MessageBoxAddAccountSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account type cannot be null.
        /// </summary>
        public static string MessageBoxButtonValidationAccountTypeFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationAccountTypeFkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account currency type cannot be blank.
        /// </summary>
        public static string MessageBoxButtonValidationCurrencyFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationCurrencyFkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account name cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationNameError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationNameError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an error updating. Please try again.
        /// </summary>
        public static string MessageBoxButtonValidErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxButtonValidErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidErrorOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxButtonValidErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account was added successfully.
        /// </summary>
        public static string MessageBoxButtonValidSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxButtonValidSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidSuccessOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxButtonValidSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidSuccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account, please retry.
        /// </summary>
        public static string MessageBoxDeleteAccountErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxDeleteAccountErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxDeleteAccountErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?{0}All associated items will also be deleted. Please note, this may take more or less time depending on the amount of data to be deleted.
        /// </summary>
        public static string MessageBoxDeleteAccountQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxDeleteAccountQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionNoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxDeleteAccountQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxDeleteAccountQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestionYesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account successfully deleted.
        /// </summary>
        public static string MessageBoxDeleteAccountSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxDeleteAccountSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxDeleteAccountSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountSuccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxEditAccountErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account was successfully edited.
        /// </summary>
        public static string MessageBoxEditAccountSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxValidAccountErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidAccountErrorOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxValidAccountErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidAccountErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account name :.
        /// </summary>
        public static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
    }
}
