//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Sql.Resources.Resx.DbContextHelperSetDefaultValues {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbContextHelperSetDefaultValuesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbContextHelperSetDefaultValuesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Sql.Resources.Resx.DbContextHelperSetDefaultValues.DbContextHelperSetD" +
                            "efaultValuesResources", typeof(DbContextHelperSetDefaultValuesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank card.
        /// </summary>
        internal static string DefaultTModePaymentNameBankCard {
            get {
                return ResourceManager.GetString("DefaultTModePaymentNameBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank direct debit.
        /// </summary>
        internal static string DefaultTModePaymentNameBankDirectDebit {
            get {
                return ResourceManager.GetString("DefaultTModePaymentNameBankDirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfer.
        /// </summary>
        internal static string DefaultTModePaymentNameBankTransfer {
            get {
                return ResourceManager.GetString("DefaultTModePaymentNameBankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string DefaultTPlaceNameInternet {
            get {
                return ResourceManager.GetString("DefaultTPlaceNameInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyDaily {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which happens every day.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyDailyDefinition {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyDailyDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyMonthly {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is done every month.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyMonthlyDefinition {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyMonthlyDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyWeekly {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is done every week.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyWeeklyDefinition {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyWeeklyDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyYearly {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is done every year.
        /// </summary>
        internal static string DefaultTRecursiveFrequencyYearlyDefinition {
            get {
                return ResourceManager.GetString("DefaultTRecursiveFrequencyYearlyDefinition", resourceCulture);
            }
        }
    }
}
