//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.MainPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.MainPage.MainPageResources", typeof(MainPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the new database.
        /// </summary>
        internal static string MessageBoxAddDataBaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur.
        /// </summary>
        internal static string MessageBoxAddDataBaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxAddDataBaseOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database was successfully added.
        /// </summary>
        internal static string MessageBoxAddDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxAddDataBaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        internal static string MessageBoxImportDatabaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxImportDatabaseErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur.
        /// </summary>
        internal static string MessageBoxImportDatabaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database import operation was successful.
        /// </summary>
        internal static string MessageBoxImportDatabaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxImportDatabaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxImportDatabaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete cloud databases if it also exists ?.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseDropboxQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseDropboxQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseDropboxQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseDropboxQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseQuestionCancelButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all database selected ?.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All databases have been deleted.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxRemoveDataBaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessTitle", resourceCulture);
            }
        }
    }
}
