//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Pages.RecordExpensePage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecordExpensePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordExpensePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Pages.RecordExpensePage.RecordExpensePageResources", typeof(RecordExpensePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDeleteContent {
            get {
                return ResourceManager.GetString("ButtonDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is pointed :.
        /// </summary>
        internal static string CheckBoxPointedContent {
            get {
                return ResourceManager.GetString("CheckBoxPointedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the account :.
        /// </summary>
        internal static string ComboBoxAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        internal static string ComboBoxBackgroundHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBackgroundHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type :.
        /// </summary>
        internal static string ComboBoxCategoryTypeHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxCategoryTypeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment :.
        /// </summary>
        internal static string ComboBoxModePaymentHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxModePaymentHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place :.
        /// </summary>
        internal static string ComboBoxPlaceHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        internal static string DatePickerWhenHintAssist {
            get {
                return ResourceManager.GetString("DatePickerWhenHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxAddHistoryError {
            get {
                return ResourceManager.GetString("MessageBoxAddHistoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to record a new expense ?.
        /// </summary>
        internal static string MessageBoxAddHistoryQuestion {
            get {
                return ResourceManager.GetString("MessageBoxAddHistoryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense record was added successfully.
        /// </summary>
        internal static string MessageBoxAddHistorySuccess {
            get {
                return ResourceManager.GetString("MessageBoxAddHistorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxEditAccountError {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully edited.
        /// </summary>
        internal static string MessageBoxEditAccountSuccess {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxEditCategoryError {
            get {
                return ResourceManager.GetString("MessageBoxEditCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type was successfully edited.
        /// </summary>
        internal static string MessageBoxEditCategorySuccess {
            get {
                return ResourceManager.GetString("MessageBoxEditCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxEditModePaymentError {
            get {
                return ResourceManager.GetString("MessageBoxEditModePaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment was successfully edited.
        /// </summary>
        internal static string MessageBoxEditModePaymentSuccess {
            get {
                return ResourceManager.GetString("MessageBoxEditModePaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxEditPlaceError {
            get {
                return ResourceManager.GetString("MessageBoxEditPlaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place was successfully edited.
        /// </summary>
        internal static string MessageBoxEditPlaceSuccess {
            get {
                return ResourceManager.GetString("MessageBoxEditPlaceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method cannot be changed or deleted.
        /// </summary>
        internal static string MessageBoxModePaymentCantEdit {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This place cannot be changed or deleted.
        /// </summary>
        internal static string MessageBoxPlaceCantEdit {
            get {
                return ResourceManager.GetString("MessageBoxPlaceCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account cannot be null, please select an account.
        /// </summary>
        internal static string MessageBoxValidationAccountFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationAccountFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type cannot be null, please select a category type.
        /// </summary>
        internal static string MessageBoxValidationCategoryTypeFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationCategoryTypeFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be null, please select a date.
        /// </summary>
        internal static string MessageBoxValidationDateError {
            get {
                return ResourceManager.GetString("MessageBoxValidationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty, please enter a description.
        /// </summary>
        internal static string MessageBoxValidationDescriptionError {
            get {
                return ResourceManager.GetString("MessageBoxValidationDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment cannot be null, please select a mode payment.
        /// </summary>
        internal static string MessageBoxValidationModePaymentFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationModePaymentFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place cannot be null, please select a place.
        /// </summary>
        internal static string MessageBoxValidationPlaceFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationPlaceFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, please enter a valid value.
        /// </summary>
        internal static string MessageBoxValidationValueError {
            get {
                return ResourceManager.GetString("MessageBoxValidationValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string TextBoxDescriptionHintAssist {
            get {
                return ResourceManager.GetString("TextBoxDescriptionHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value :.
        /// </summary>
        internal static string TextBoxValueHintAssist {
            get {
                return ResourceManager.GetString("TextBoxValueHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        internal static string TimePickerWhenHintAssist {
            get {
                return ResourceManager.GetString("TimePickerWhenHintAssist", resourceCulture);
            }
        }
    }
}
