//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.DetailedRecordManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailedRecordManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DetailedRecordManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.DetailedRecordManagement.DetailedRecordMana" +
                            "gementResources", typeof(DetailedRecordManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new history.
        /// </summary>
        public static string ButtonAddNewHistoryText {
            get {
                return ResourceManager.GetString("ButtonAddNewHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refocus.
        /// </summary>
        public static string ButtonRefocusText {
            get {
                return ResourceManager.GetString("ButtonRefocusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdateText {
            get {
                return ResourceManager.GetString("ButtonUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonValidText {
            get {
                return ResourceManager.GetString("ButtonValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the account :.
        /// </summary>
        public static string ComboBoxAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        public static string ComboBoxBackgroundHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBackgroundHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type :.
        /// </summary>
        public static string ComboBoxCategoryTypeHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxCategoryTypeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment :.
        /// </summary>
        public static string ComboBoxModePaymentHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxModePaymentHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        public static string ComboBoxPlaceCityHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceCityHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        public static string ComboBoxPlaceCountryHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceCountryHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place :.
        /// </summary>
        public static string ComboBoxPlaceHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string DatePickerWhenHintAssist {
            get {
                return ResourceManager.GetString("DatePickerWhenHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added on :.
        /// </summary>
        public static string LabelTextAddedOn {
            get {
                return ResourceManager.GetString("LabelTextAddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the account :.
        /// </summary>
        public static string LabelTextOnTheAccount {
            get {
                return ResourceManager.GetString("LabelTextOnTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed on :.
        /// </summary>
        public static string LabelTextPointedOn {
            get {
                return ResourceManager.GetString("LabelTextPointedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxAddHistoryErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddHistoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to register a new banking transaction ?.
        /// </summary>
        public static string MessageBoxAddHistoryQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddHistoryQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense record was added successfully.
        /// </summary>
        public static string MessageBoxAddHistorySuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddHistorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please try again.
        /// </summary>
        public static string MessageBoxDeleteHistoryErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxDeleteHistoryErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxDeleteHistoryErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Record was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteHistoryNoUseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryNoUseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record ?.
        /// </summary>
        public static string MessageBoxDeleteHistoryQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxDeleteHistoryQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this record ?.
        /// </summary>
        public static string MessageBoxDeleteHistoryQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxDeleteHistoryQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record was successfully deleted.
        /// </summary>
        public static string MessageBoxDeleteHistorySuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxDeleteHistorySuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistorySuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxDeleteHistorySuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistorySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record and all relative element was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteHistoryUseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHistoryUseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is in use. Are you sure you want to delete this record and everything linked to it ?.
        /// </summary>
        public static string MessageBoxDeleteUseRecordQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxDeleteUseRecordQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account cannot be null, please select an account.
        /// </summary>
        public static string MessageBoxValidationAccountFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationAccountFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type cannot be null, please select a category type.
        /// </summary>
        public static string MessageBoxValidationCategoryTypeFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationCategoryTypeFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be null, please select a date.
        /// </summary>
        public static string MessageBoxValidationDateError {
            get {
                return ResourceManager.GetString("MessageBoxValidationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty, please enter a description.
        /// </summary>
        public static string MessageBoxValidationDescriptionError {
            get {
                return ResourceManager.GetString("MessageBoxValidationDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment cannot be null, please select a mode payment.
        /// </summary>
        public static string MessageBoxValidationModePaymentFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationModePaymentFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place cannot be null, please select a place.
        /// </summary>
        public static string MessageBoxValidationPlaceFkError {
            get {
                return ResourceManager.GetString("MessageBoxValidationPlaceFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, please enter a valid value.
        /// </summary>
        public static string MessageBoxValidationValueError {
            get {
                return ResourceManager.GetString("MessageBoxValidationValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxValidHistoryErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidHistoryErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxValidHistoryErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidHistoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating the history. Please try again.
        /// </summary>
        public static string MessageBoxValidNewHistoryErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxValidNewHistoryErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxValidNewHistoryErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made to this record ?.
        /// </summary>
        public static string MessageBoxValidNewHistoryQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxValidNewHistoryQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageBoxValidNewHistoryQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxValidNewHistoryQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxValidNewHistoryQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed operation :.
        /// </summary>
        public static string PointedOperation {
            get {
                return ResourceManager.GetString("PointedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string TextBoxDescriptionHintAssist {
            get {
                return ResourceManager.GetString("TextBoxDescriptionHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value :.
        /// </summary>
        public static string TextBoxValueHintAssist {
            get {
                return ResourceManager.GetString("TextBoxValueHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        public static string TimePickerWhenHintAssist {
            get {
                return ResourceManager.GetString("TimePickerWhenHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in progress.
        /// </summary>
        public static string TitleIsDirty {
            get {
                return ResourceManager.GetString("TitleIsDirty", resourceCulture);
            }
        }
    }
}
