//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.CurrencySymbolSummaryContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurrencySymbolSummaryContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencySymbolSummaryContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.CurrencySymbolSummaryContentPa" +
                            "ge.CurrencySymbolSummaryContentPageResources", typeof(CurrencySymbolSummaryContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidText {
            get {
                return ResourceManager.GetString("ButtonValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency value :.
        /// </summary>
        internal static string CustomPopupEntryPlaceHolderText {
            get {
                return ResourceManager.GetString("CustomPopupEntryPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding currency symbol, please retry.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyErrorMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyErrorOkButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyErrorTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add &quot;{0}&quot; as a currency ?.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyQuestionMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyQuestionNoButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new currency ?.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyQuestionTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MesageBoxAddNewCurrencyQuestionYesButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencyQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol was successfully added.
        /// </summary>
        internal static string MesageBoxAddNewCurrencySuccessMessage {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MesageBoxAddNewCurrencySuccessOkButton {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencySuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MesageBoxAddNewCurrencySuccessTitle {
            get {
                return ResourceManager.GetString("MesageBoxAddNewCurrencySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting currency symbol, please retry.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this currency? {0}All accounts that use this currency will also be deleted, be careful the operation may take more or less time depending on the number of data to be deleted.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol and all related accounts were successfully deleted.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxHandleCurrencyDeleteSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyDeleteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing currency symbol, please retry.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to edit this currency ?.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol was successfully edited.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBoxHandleCurrencyEditSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxHandleCurrencyEditSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol already exist.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorAlreadyExistOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorAlreadyExistOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorAlreadyExistTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol can&apos;t be empty.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorEmptyMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorEmptyOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorEmptyOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValidateCurrencySymbolErrorEmptyTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateCurrencySymbolErrorEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new currency symbol :.
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
    }
}
