//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.DashBoardManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashBoardManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DashBoardManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.DashBoardManagement.DashBoardManagementReso" +
                            "urces", typeof(DashBoardManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of the month :.
        /// </summary>
        public static string ComboBoxMonthHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxMonthHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of the year :.
        /// </summary>
        public static string ComboBoxYearsHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxYearsHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time :.
        /// </summary>
        public static string ElapsedTimeLoadingDataText {
            get {
                return ResourceManager.GetString("ElapsedTimeLoadingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelTextCategory {
            get {
                return ResourceManager.GetString("LabelTextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed.
        /// </summary>
        public static string LabelTextChecked {
            get {
                return ResourceManager.GetString("LabelTextChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelTextDescription {
            get {
                return ResourceManager.GetString("LabelTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string LabelTextPaymentMode {
            get {
                return ResourceManager.GetString("LabelTextPaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string LabelTextPlace {
            get {
                return ResourceManager.GetString("LabelTextPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelTextValue {
            get {
                return ResourceManager.GetString("LabelTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional dates are available.
        /// </summary>
        public static string MessageBoxAddMonthErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddMonthErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAddMonthErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressCheck {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to {0} this record ?{1}.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressMessage {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressNoButton {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm update of this record.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressTitle {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpoint.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressUnCheck {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressUnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageBoxCollectionViewVHistoryOnLongPressYesButton {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lower dates are available.
        /// </summary>
        public static string MessageBoxRemoveMonthErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxRemoveMonthErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxRemoveMonthErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record(s) found on.
        /// </summary>
        public static string RecordFoundOn {
            get {
                return ResourceManager.GetString("RecordFoundOn", resourceCulture);
            }
        }
    }
}
