//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.WelcomeManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WelcomeManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public WelcomeManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.WelcomeManagement.WelcomeManagementResource" +
                            "s", typeof(WelcomeManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new database....
        /// </summary>
        public static string ActivityIndicatorCreateNewDatabase {
            get {
                return ResourceManager.GetString("ActivityIndicatorCreateNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected databases to cloud storage... Please wait.
        /// </summary>
        public static string ActivityIndicatorExportDatabaseToCloud {
            get {
                return ResourceManager.GetString("ActivityIndicatorExportDatabaseToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to local storage... Please wait.
        /// </summary>
        public static string ActivityIndicatorExportDatabaseToLocal {
            get {
                return ResourceManager.GetString("ActivityIndicatorExportDatabaseToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing the database from cloud... Please wait.
        /// </summary>
        public static string ActivityIndicatorImportDatabaseFromCloud {
            get {
                return ResourceManager.GetString("ActivityIndicatorImportDatabaseFromCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing the database from local storage... Please wait.
        /// </summary>
        public static string ActivityIndicatorImportDatabaseFromLocal {
            get {
                return ResourceManager.GetString("ActivityIndicatorImportDatabaseFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening database &quot;{0}&quot;....
        /// </summary>
        public static string ActivityIndicatorOpenDatabase {
            get {
                return ResourceManager.GetString("ActivityIndicatorOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup operation was successful.
        /// </summary>
        public static string ButtonExportDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("ButtonExportDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string ButtonImportDataBaseErrorMessage {
            get {
                return ResourceManager.GetString("ButtonImportDataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database import operation was successful.
        /// </summary>
        public static string ButtonImportDataBaseImportSucessMessage {
            get {
                return ResourceManager.GetString("ButtonImportDataBaseImportSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the databases selected in the cloud appear to be less recent than those currently available in local storage.{0}Are you sure you want to import these cloud databases into local storage?.
        /// </summary>
        public static string CloudDatabaseOutdatedWarningQuestionMessage {
            get {
                return ResourceManager.GetString("CloudDatabaseOutdatedWarningQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CloudDatabaseOutdatedWarningQuestionNoButton {
            get {
                return ResourceManager.GetString("CloudDatabaseOutdatedWarningQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string CloudDatabaseOutdatedWarningQuestionTitle {
            get {
                return ResourceManager.GetString("CloudDatabaseOutdatedWarningQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CloudDatabaseOutdatedWarningQuestionYesButton {
            get {
                return ResourceManager.GetString("CloudDatabaseOutdatedWarningQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the new database.
        /// </summary>
        public static string MessageBoxAddDataBaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur.
        /// </summary>
        public static string MessageBoxAddDataBaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddDataBaseOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database was successfully added.
        /// </summary>
        public static string MessageBoxAddDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAddDataBaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddDataBaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string MessageBoxExportDataBaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxExportDataBaseErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxExportDataBaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following databases could not be exported :{0}{1}.
        /// </summary>
        public static string MessageBoxExportDataBaseExportErrorSomeDatabaseMessage {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseExportErrorSomeDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxExportDataBaseExportErrorSomeDatabaseOkButton {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseExportErrorSomeDatabaseOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxExportDataBaseExportErrorSomeDatabaseTitle {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseExportErrorSomeDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup operation was successful.
        /// </summary>
        public static string MessageBoxExportDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxExportDataBaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxExportDataBaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxExportDataBaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string MessageBoxImportDatabaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxImportDatabaseErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur.
        /// </summary>
        public static string MessageBoxImportDatabaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database import operation was successful.
        /// </summary>
        public static string MessageBoxImportDatabaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxImportDatabaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxImportDatabaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxImportDatabaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the export folder ?.
        /// </summary>
        public static string MessageBoxOpenExportFolderQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxOpenExportFolderQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete cloud databases if it also exists ?.
        /// </summary>
        public static string MessageBoxRemoveDataBaseDropboxQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxRemoveDataBaseDropboxQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxRemoveDataBaseDropboxQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxRemoveDataBaseDropboxQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseDropboxQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxRemoveDataBaseQuestionCancelButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all database selected ?.
        /// </summary>
        public static string MessageBoxRemoveDataBaseQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxRemoveDataBaseQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxRemoveDataBaseQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All databases have been deleted.
        /// </summary>
        public static string MessageBoxRemoveDataBaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxRemoveDataBaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxRemoveDataBaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveDataBaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxUseOutdatedWarningQuestionCancelButton {
            get {
                return ResourceManager.GetString("MessageBoxUseOutdatedWarningQuestionCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to use this database?{0}Your local version is outdated, we recommend that you sync it before using it.
        /// </summary>
        public static string MessageBoxUseOutdatedWarningQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxUseOutdatedWarningQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxUseOutdatedWarningQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxUseOutdatedWarningQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxUseOutdatedWarningQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxUseOutdatedWarningQuestionYesButton", resourceCulture);
            }
        }
    }
}
