using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Globalization;

namespace MyExpenses.SourceGenerators;

[Generator]
public sealed class DirtyTrackingGenerator : IIncrementalGenerator
{
    private const string DirtyTrackingAttributeMetadataName = "MyExpenses.SourceGenerators.DirtyTrackingAttribute";
    private const string DirtyTrackedPropertyAttributeMetadataName = "MyExpenses.SourceGenerators.DirtyTrackedPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Injection des attributs (Public + Nullable Enabled)
        context.RegisterPostInitializationOutput(i =>
        {
            var ns = "MyExpenses.SourceGenerators";
            i.AddSource("DirtyTrackingAttributes.g.cs", $@"// <auto-generated/>
#nullable enable

namespace {ns};

[System.AttributeUsage(System.AttributeTargets.Class)]
public sealed class DirtyTrackingAttribute : System.Attribute {{ }}

public enum DirtyComparisonKind {{ Auto, NumericWithTolerance }}

[System.AttributeUsage(System.AttributeTargets.Property)]
public sealed class DirtyTrackedPropertyAttribute : System.Attribute 
{{
    public DirtyTrackedPropertyAttribute(DirtyComparisonKind comparisonKind = DirtyComparisonKind.Auto) 
        => ComparisonKind = comparisonKind;

    public DirtyComparisonKind ComparisonKind {{ get; }}
    public double Tolerance {{ get; set; }} = 0.0001;
}}");
        });

        var trackedClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DirtyTrackingAttributeMetadataName,
                predicate: static (_, _) => true,
                transform: static (context, _) => (INamedTypeSymbol)context.TargetSymbol);

        context.RegisterSourceOutput(trackedClasses, static (spc, classSymbol) =>
        {
            var source = GenerateForClass(classSymbol);
            spc.AddSource($"{classSymbol.Name}.DirtyTracking.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateForClass(INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var trackedProperties = GetTrackedProperties(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable"); // On active les nullables ici aussi
        sb.AppendLine();

        if (ns != null) sb.AppendLine($"namespace {ns};\n");

        sb.AppendLine($"public partial class {classSymbol.Name}\n{{");

        GenerateFields(sb, trackedProperties);
        GeneratePropertyDirtyChecks(sb, trackedProperties);
        GenerateTrackingMethods(sb, trackedProperties);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<IPropertySymbol> GetTrackedProperties(INamedTypeSymbol classSymbol)
    {
        return classSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == DirtyTrackedPropertyAttributeMetadataName))
            .ToList();
    }

    private static void GenerateFields(StringBuilder sb, IEnumerable<IPropertySymbol> props)
    {
        foreach (var prop in props)
        {
            // Note: Sans pragma disable, tu auras sûrement un warning CS8618 ici
            // si la propriété n'est pas un type nullable (ex: string vs string?)
            sb.AppendLine($"    private {prop.Type.ToDisplayString()} _original{prop.Name};");
        }
        sb.AppendLine();
    }

    private static void GeneratePropertyDirtyChecks(StringBuilder sb, IEnumerable<IPropertySymbol> props)
    {
        foreach (var prop in props)
        {
            var logic = GetDirtyLogic(prop);
            sb.AppendLine($"    public bool Is{prop.Name}Dirty => {logic}");
        }
    }

    private static string GetDirtyLogic(IPropertySymbol prop)
    {
        var attr = prop.GetAttributes()
            .First(a => a.AttributeClass?.ToDisplayString() == DirtyTrackedPropertyAttributeMetadataName);

        var kind = attr.ConstructorArguments.FirstOrDefault().Value is int i ? i : 0;
        var tolerance = (double)(attr.NamedArguments.FirstOrDefault(x => x.Key == "Tolerance").Value.Value ?? 0.0001);

        var isNested = IsTypeTracked(prop.Type);
        var isSimple = prop.Type.IsValueType || prop.Type.SpecialType == SpecialType.System_String ||
                       prop.Type.TypeKind == TypeKind.Enum;

        if (isNested)
            return $"_original{prop.Name} != {prop.Name} || ({prop.Name}?.IsDirty ?? false);";

        if (kind == 1)
            return $"System.Math.Abs((double)(_original{prop.Name} - {prop.Name})) > {tolerance.ToString(CultureInfo.InvariantCulture)};";

        return !isSimple
            ? $"!System.Collections.Generic.EqualityComparer<{prop.Type.ToDisplayString()}>.Default.Equals(_original{prop.Name}, {prop.Name});"
            : $"_original{prop.Name} != {prop.Name};";
    }

    private static void GenerateTrackingMethods(StringBuilder sb, List<IPropertySymbol> props)
    {
        var isDirtyExpression = props.Count == 0 ? "false" : string.Join(" || ", props.Select(p => $"Is{p.Name}Dirty"));
        sb.AppendLine($"\n    public bool IsDirty => {isDirtyExpression};");

        sb.AppendLine("\n    public void AcceptChanges()\n    {");
        foreach (var prop in props)
        {
            sb.AppendLine($"        _original{prop.Name} = {prop.Name};");
            if (IsTypeTracked(prop.Type))
                sb.AppendLine($"        {prop.Name}?.AcceptChanges();");
        }
        sb.AppendLine("    }");

        sb.AppendLine("\n    public void RejectChanges()\n    {");
        foreach (var prop in props)
        {
            sb.AppendLine($"        {prop.Name} = _original{prop.Name};");
            if (IsTypeTracked(prop.Type))
                sb.AppendLine($"        {prop.Name}?.RejectChanges();");
        }
        sb.AppendLine("    }");
    }

    private static bool IsTypeTracked(ITypeSymbol type) =>
        type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == DirtyTrackingAttributeMetadataName);
}