//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.AddDatabaseFileContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddDatabaseFileContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddDatabaseFileContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.AddDatabaseFileContentPage.AddDatabaseFileContentPageResources", typeof(AddDatabaseFileContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file name :.
        /// </summary>
        internal static string CustomEntryControlPlaceholderText {
            get {
                return ResourceManager.GetString("CustomEntryControlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file name already exist.
        /// </summary>
        internal static string MessageBoxDatabaseAlreadyExistErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseAlreadyExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxDatabaseAlreadyExistErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseAlreadyExistErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxDatabaseAlreadyExistErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseAlreadyExistErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file name contains incorrect characters.
        /// </summary>
        internal static string MessageBoxDatabaseFilenameContainsIncorrectCharErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseFilenameContainsIncorrectCharErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxDatabaseFilenameContainsIncorrectCharErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseFilenameContainsIncorrectCharErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxDatabaseFilenameContainsIncorrectCharErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxDatabaseFilenameContainsIncorrectCharErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file name cannot be empty.
        /// </summary>
        internal static string MessageBoxEmptyNameErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxEmptyNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxEmptyNameErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxEmptyNameErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxEmptyNameErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxEmptyNameErrorTitle", resourceCulture);
            }
        }
    }
}
