//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.BankTransferManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankTransferManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BankTransferManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.BankTransferManagement.BankTransferManageme" +
                            "ntResources", typeof(BankTransferManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonPrepareCancelContent {
            get {
                return ResourceManager.GetString("ButtonPrepareCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonPrepareValidContent {
            get {
                return ResourceManager.GetString("ButtonPrepareValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonPreviewCancelContent {
            get {
                return ResourceManager.GetString("ButtonPreviewCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonPreviewValidContent {
            get {
                return ResourceManager.GetString("ButtonPreviewValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type :.
        /// </summary>
        public static string ComboBoxCategoryTypeHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxCategoryTypeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From account :.
        /// </summary>
        public static string ComboBoxFromAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxFromAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment :.
        /// </summary>
        public static string ComboBoxModePaymentHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxModePaymentHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To account :.
        /// </summary>
        public static string ComboBoxToAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxToAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string LabelTextTransferDate {
            get {
                return ResourceManager.GetString("LabelTextTransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount :.
        /// </summary>
        public static string LabelTextTransferValue {
            get {
                return ResourceManager.GetString("LabelTextTransferValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationDateError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting account cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationFromAccountFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationFromAccountFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main reason cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationMainReasonError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationMainReasonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival account cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationToAccountFkError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationToAccountFkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidationValueError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidationValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidBankTransferPrepareCategoryIsNullError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidBankTransferPrepareCategoryIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment cannot be empty.
        /// </summary>
        public static string MessageBoxButtonValidBankTransferPrepareModePaymentIsNullError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidBankTransferPrepareModePaymentIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxButtonValidBankTransferPreviewError {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidBankTransferPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to make another bank transfer ?.
        /// </summary>
        public static string MessageBoxButtonValidBankTransferPreviewNewTransferQuestion {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidBankTransferPreviewNewTransferQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transfer has been successfully completed.
        /// </summary>
        public static string MessageBoxButtonValidBankTransferPreviewSuccess {
            get {
                return ResourceManager.GetString("MessageBoxButtonValidBankTransferPreviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxEditAccountError {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully edited.
        /// </summary>
        public static string MessageBoxEditAccountSuccess {
            get {
                return ResourceManager.GetString("MessageBoxEditAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional reason :.
        /// </summary>
        public static string TextBoxAdditionalReasonHintAssist {
            get {
                return ResourceManager.GetString("TextBoxAdditionalReasonHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main reason :.
        /// </summary>
        public static string TextBoxMainReasonHintAssist {
            get {
                return ResourceManager.GetString("TextBoxMainReasonHintAssist", resourceCulture);
            }
        }
    }
}
