//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.ModePaymentManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModePaymentManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ModePaymentManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.ModePaymentManagement.ModePaymentManagement" +
                            "Resources", typeof(ModePaymentManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteContent {
            get {
                return ResourceManager.GetString("ButtonDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxAddModePaymentErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddModePaymentErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAddModePaymentErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new mode payment has been added successfully.
        /// </summary>
        public static string MessageBoxAddModePaymentSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddModePaymentSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAddModePaymentSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddModePaymentSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxDeleteModePaymentError {
            get {
                return ResourceManager.GetString("MessageBoxDeleteModePaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteModePaymentNoUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteModePaymentNoUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode payment is in use. Are you sure you want to delete this mode payment and everything linked to it ?.
        /// </summary>
        public static string MessageBoxDeleteModePaymentUseQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteModePaymentUseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment and all relative element was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteModePaymentUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteModePaymentUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this mode payment ?.
        /// </summary>
        public static string MessageBoxDeleteQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxEditModePaymentErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditModePaymentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment was successfully edited.
        /// </summary>
        public static string MessageBoxEditModePaymentSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditModePaymentSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method cannot be changed or deleted.
        /// </summary>
        public static string MessageBoxModePaymentCantEditMessage {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentCantEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxModePaymentCantEditOkButton {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentCantEditOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxModePaymentCantEditTitle {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentCantEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment already exist.
        /// </summary>
        public static string MessageBoxModePaymentNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxModePaymentNameAlreadyExistsOkButton {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameAlreadyExistsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxModePaymentNameAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment name cannot be empty.
        /// </summary>
        public static string MessageBoxModePaymentNameEmptyErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxModePaymentNameEmptyErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameEmptyErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxModePaymentNameEmptyErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxModePaymentNameEmptyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment method already exists.
        /// </summary>
        public static string MessageBoxValidateModePaymentErrorAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateModePaymentErrorAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment name :.
        /// </summary>
        public static string TextBoxModePaymentName {
            get {
                return ResourceManager.GetString("TextBoxModePaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or edit a payment method.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
