//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Windows.AddEditRecurrentExpenseWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddEditRecurrentExpenseWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddEditRecurrentExpenseWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Windows.AddEditRecurrentExpenseWindow.AddEditRecurr" +
                            "entExpenseWindowResources", typeof(AddEditRecurrentExpenseWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force deactivate :.
        /// </summary>
        internal static string CheckBoxForceDeactivate {
            get {
                return ResourceManager.GetString("CheckBoxForceDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active :.
        /// </summary>
        internal static string CheckBoxIsActive {
            get {
                return ResourceManager.GetString("CheckBoxIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string ComboBoxAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        internal static string ComboBoxBackgroundHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBackgroundHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category :.
        /// </summary>
        internal static string ComboBoxCategoryTypeHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxCategoryTypeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency :.
        /// </summary>
        internal static string ComboBoxFrequencyHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxFrequencyHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        internal static string ComboBoxPlaceCityHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceCityHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string ComboBoxPlaceCountryHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceCountryHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place :.
        /// </summary>
        internal static string ComboBoxPlaceHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxPlaceHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date :.
        /// </summary>
        internal static string DatePickerStartDateHintAssist {
            get {
                return ResourceManager.GetString("DatePickerStartDateHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string TextBoxDescriptionHintAssist {
            get {
                return ResourceManager.GetString("TextBoxDescriptionHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next due date :.
        /// </summary>
        internal static string TextBoxNextDueDateHintAssist {
            get {
                return ResourceManager.GetString("TextBoxNextDueDateHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note :.
        /// </summary>
        internal static string TextBoxNoteHintAssist {
            get {
                return ResourceManager.GetString("TextBoxNoteHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of executions :.
        /// </summary>
        internal static string TextBoxRecursiveCountHintAssist {
            get {
                return ResourceManager.GetString("TextBoxRecursiveCountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number :.
        /// </summary>
        internal static string TextBoxRecursiveTotalHintAssist {
            get {
                return ResourceManager.GetString("TextBoxRecursiveTotalHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value :.
        /// </summary>
        internal static string TextBoxValueHintAssist {
            get {
                return ResourceManager.GetString("TextBoxValueHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or edit a recurring expense.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
