//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Windows.AddAccountWindow {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddEditAccountWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddEditAccountWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Windows.AddEditAccountWindow.AddEditAccountWindowResources", typeof(AddEditAccountWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category :.
        /// </summary>
        internal static string ComboBoxAccountCategoryType {
            get {
                return ResourceManager.GetString("ComboBoxAccountCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency :.
        /// </summary>
        internal static string ComboBoxAccountCurrency {
            get {
                return ResourceManager.GetString("ComboBoxAccountCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type :.
        /// </summary>
        internal static string ComboBoxAccountType {
            get {
                return ResourceManager.GetString("ComboBoxAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the account active ?.
        /// </summary>
        internal static string LabelIsAccountActive {
            get {
                return ResourceManager.GetString("LabelIsAccountActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxAddAccountTypeError {
            get {
                return ResourceManager.GetString("MessageBoxAddAccountTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account type was successfully added.
        /// </summary>
        internal static string MessageBoxAddAccountTypeSuccess {
            get {
                return ResourceManager.GetString("MessageBoxAddAccountTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        internal static string MessageBoxAddCurrencyError {
            get {
                return ResourceManager.GetString("MessageBoxAddCurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new currency has been added successfully.
        /// </summary>
        internal static string MessageBoxAddCurrencySuccess {
            get {
                return ResourceManager.GetString("MessageBoxAddCurrencySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account currency cannot be empty.
        /// </summary>
        internal static string MsgBoxErrorAccountCurrencyCannotByEmpty {
            get {
                return ResourceManager.GetString("MsgBoxErrorAccountCurrencyCannotByEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account already exists with this name.
        /// </summary>
        internal static string MsgBoxErrorAccountNameAlreadyExists {
            get {
                return ResourceManager.GetString("MsgBoxErrorAccountNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name cannot be empty.
        /// </summary>
        internal static string MsgBoxErrorAccountNameCannotByEmpty {
            get {
                return ResourceManager.GetString("MsgBoxErrorAccountNameCannotByEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance departure description cannot be empty.
        /// </summary>
        internal static string MsgBoxErrorAccountStartingBalanceDescriptionCannotByEmpty {
            get {
                return ResourceManager.GetString("MsgBoxErrorAccountStartingBalanceDescriptionCannotByEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type cannot be empty.
        /// </summary>
        internal static string MsgBoxErrorAccountTypeCannotByEmpty {
            get {
                return ResourceManager.GetString("MsgBoxErrorAccountTypeCannotByEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name :.
        /// </summary>
        internal static string TextBoxAccountName {
            get {
                return ResourceManager.GetString("TextBoxAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting balance :.
        /// </summary>
        internal static string TextBoxAccountStartingBalance {
            get {
                return ResourceManager.GetString("TextBoxAccountStartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the starting balance :.
        /// </summary>
        internal static string TextBoxAccountStartingBalanceDescription {
            get {
                return ResourceManager.GetString("TextBoxAccountStartingBalanceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to button valid content.
        /// </summary>
        internal static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to button delete content.
        /// </summary>
        internal static string ButtonDeleteContent {
            get {
                return ResourceManager.GetString("ButtonDeleteContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to button cancel content.
        /// </summary>
        internal static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to messagebox delete account no use.
        /// </summary>
        internal static string MessageBoxDeleteAccountNoUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountNoUseSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to messagebox delete account use question.
        /// </summary>
        internal static string MessageBoxDeleteAccountUseQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountUseQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to messagebox delete account use success.
        /// </summary>
        internal static string MessageBoxDeleteAccountUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountUseSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to messagebox delete account error.
        /// </summary>
        internal static string MessageBoxDeleteAccountError {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountUseSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to messagebox delete account question.
        /// </summary>
        internal static string MessageBoxDeleteAccountQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TitleWindow.
        /// </summary>
        internal static string TitleWindow {
            get {
                return ResourceManager.GetString("TitleWindow", resourceCulture);
            }
        }
    }
}
