//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.GeneralAccountSetupContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralAccountSetupContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralAccountSetupContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.GeneralAccountSetupContentPage" +
                            ".GeneralAccountSetupContentPageResources", typeof(GeneralAccountSetupContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account(s) Management.
        /// </summary>
        internal static string ButtonTextAccountManagement {
            get {
                return ResourceManager.GetString("ButtonTextAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color management.
        /// </summary>
        internal static string ButtonTextColorManagement {
            get {
                return ResourceManager.GetString("ButtonTextColorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency symbol management.
        /// </summary>
        internal static string ButtonTextCurrencySymbolManagement {
            get {
                return ResourceManager.GetString("ButtonTextCurrencySymbolManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location management.
        /// </summary>
        internal static string ButtonTextLocationManagement {
            get {
                return ResourceManager.GetString("ButtonTextLocationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing account types.
        /// </summary>
        internal static string ButtonTextManagingAccountTypes {
            get {
                return ResourceManager.GetString("ButtonTextManagingAccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing category types.
        /// </summary>
        internal static string ButtonTextManagingCategoryTypes {
            get {
                return ResourceManager.GetString("ButtonTextManagingCategoryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method management.
        /// </summary>
        internal static string ButtonTextPaymentMethodManagement {
            get {
                return ResourceManager.GetString("ButtonTextPaymentMethodManagement", resourceCulture);
            }
        }
    }
}
