//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Presentation.Resources.Resx.ExpenseResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpenseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpenseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Presentation.Resources.Resx.ExpenseResources.ExpenseResources", typeof(ExpenseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An additional reason cannot exceed {0} characters.
        /// </summary>
        public static string BankTransferViewModelValidatorAdditionalReasonTooLong {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorAdditionalReasonTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        public static string BankTransferViewModelValidatorDateRequired {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A from account is required.
        /// </summary>
        public static string BankTransferViewModelValidatorFromAccountRequired {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorFromAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A main reason is required.
        /// </summary>
        public static string BankTransferViewModelValidatorMainReasonRequired {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorMainReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A main reason cannot exceed {0} characters.
        /// </summary>
        public static string BankTransferViewModelValidatorMainReasonTooLong {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorMainReasonTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to account is required.
        /// </summary>
        public static string BankTransferViewModelValidatorToAccountRequired {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorToAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required and must be greater than zero.
        /// </summary>
        public static string BankTransferViewModelValidatorValueRequired {
            get {
                return ResourceManager.GetString("BankTransferViewModelValidatorValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonPrepareCancelContent {
            get {
                return ResourceManager.GetString("ButtonPrepareCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ButtonPrepareValidContent {
            get {
                return ResourceManager.GetString("ButtonPrepareValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonPreviewCancelContent {
            get {
                return ResourceManager.GetString("ButtonPreviewCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ButtonPreviewValidContent {
            get {
                return ResourceManager.GetString("ButtonPreviewValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is required.
        /// </summary>
        public static string CategoryTypeViewModelColorRequired {
            get {
                return ResourceManager.GetString("CategoryTypeViewModelColorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type name must be unique.
        /// </summary>
        public static string CategoryTypeViewModelNameAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryTypeViewModelNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type name is required.
        /// </summary>
        public static string CategoryTypeViewModelNameRequired {
            get {
                return ResourceManager.GetString("CategoryTypeViewModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 1 and {0} characters long.
        /// </summary>
        public static string CategoryTypeViewModelNameTooLong {
            get {
                return ResourceManager.GetString("CategoryTypeViewModelNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Type:.
        /// </summary>
        public static string ComboBoxCategoryTypeHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxCategoryTypeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the account:.
        /// </summary>
        public static string ComboBoxFromAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxFromAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        public static string ComboBoxModePaymentHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxModePaymentHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the account:.
        /// </summary>
        public static string ComboBoxToAccountHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxToAccountHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string DatePickerWhenHintAssist {
            get {
                return ResourceManager.GetString("DatePickerWhenHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account is required.
        /// </summary>
        public static string HistoryViewModelValidatorAccountViewModelRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorAccountViewModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type is required.
        /// </summary>
        public static string HistoryViewModelValidatorCategoryTypeViewModelRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorCategoryTypeViewModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date is required.
        /// </summary>
        public static string HistoryViewModelValidatorDateRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description should be between 1 and {0} characters.
        /// </summary>
        public static string HistoryViewModelValidatorDescriptionLength {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A payment method is required.
        /// </summary>
        public static string HistoryViewModelValidatorModePaymentViewModelRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorModePaymentViewModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A place is required.
        /// </summary>
        public static string HistoryViewModelValidatorPlaceViewModelRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorPlaceViewModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required.
        /// </summary>
        public static string HistoryViewModelValidatorValueRequired {
            get {
                return ResourceManager.GetString("HistoryViewModelValidatorValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional reason:.
        /// </summary>
        public static string TextBoxAdditionalReasonHintAssist {
            get {
                return ResourceManager.GetString("TextBoxAdditionalReasonHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category type name :.
        /// </summary>
        public static string TextBoxAddNewCategoryTypeName {
            get {
                return ResourceManager.GetString("TextBoxAddNewCategoryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category type name :.
        /// </summary>
        public static string TextBoxEditCategoryTypeName {
            get {
                return ResourceManager.GetString("TextBoxEditCategoryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main reason:.
        /// </summary>
        public static string TextBoxMainReasonHintAssist {
            get {
                return ResourceManager.GetString("TextBoxMainReasonHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string TextBoxValueHintAssist {
            get {
                return ResourceManager.GetString("TextBoxValueHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category type.
        /// </summary>
        public static string TitleWindowAddCategoryTypeName {
            get {
                return ResourceManager.GetString("TitleWindowAddCategoryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category type.
        /// </summary>
        public static string TitleWindowEditCategoryTypeName {
            get {
                return ResourceManager.GetString("TitleWindowEditCategoryTypeName", resourceCulture);
            }
        }
    }
}
