//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.BackupSelectorRestoreManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackupSelectorRestoreManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BackupSelectorRestoreManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.BackupSelectorRestoreManagement.BackupSelec" +
                            "torRestoreManagementResources", typeof(BackupSelectorRestoreManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ButtonContentRestore {
            get {
                return ResourceManager.GetString("ButtonContentRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        public static string MessageboxNoDatabaseSelectedMessage {
            get {
                return ResourceManager.GetString("MessageboxNoDatabaseSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageboxNoDatabaseSelectedOkButton {
            get {
                return ResourceManager.GetString("MessageboxNoDatabaseSelectedOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxNoDatabaseSelectedTitle {
            get {
                return ResourceManager.GetString("MessageboxNoDatabaseSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring the database.
        /// </summary>
        public static string MessageboxRestoreDatabaseErrorMessage {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageboxRestoreDatabaseErrorOkButton {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxRestoreDatabaseErrorTitle {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore this database ?.
        /// </summary>
        public static string MessageboxRestoreDatabaseQuestionMessage {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageboxRestoreDatabaseQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageboxRestoreDatabaseQuestionTitle {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageboxRestoreDatabaseQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful database restore.
        /// </summary>
        public static string MessageboxRestoreDatabaseSuccessMessage {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageboxRestoreDatabaseSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageboxRestoreDatabaseSuccessTitle {
            get {
                return ResourceManager.GetString("MessageboxRestoreDatabaseSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on.
        /// </summary>
        public static string TextColumnDatabaseDateBackupHeader {
            get {
                return ResourceManager.GetString("TextColumnDatabaseDateBackupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextColumnDatabaseNameHeader {
            get {
                return ResourceManager.GetString("TextColumnDatabaseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
