//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.AccountTypeManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountTypeManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AccountTypeManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.AccountTypeManagement.AccountTypeManagement" +
                            "Resources", typeof(AccountTypeManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the account type and all linked accounts.
        /// </summary>
        public static string ActivityIndicatorDeleteAccountType {
            get {
                return ResourceManager.GetString("ActivityIndicatorDeleteAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelContent {
            get {
                return ResourceManager.GetString("ButtonCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteContent {
            get {
                return ResourceManager.GetString("ButtonDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonValidContent {
            get {
                return ResourceManager.GetString("ButtonValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting account type, please retry.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this account type?{0}All accounts that use this account type will also be deleted, be careful the operation may take more or less time depending on the number of data to be deleted.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type and all related accounts were successfully deleted.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAccountTypeDeleteSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeDeleteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing currency symbol, please retry.
        /// </summary>
        public static string MessageBoxAccountTypeEditErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAccountTypeEditErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAccountTypeEditErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to edit this account type ?.
        /// </summary>
        public static string MessageBoxAccountTypeEditQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxAccountTypeEditQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxAccountTypeEditQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxAccountTypeEditQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type was successfully edited.
        /// </summary>
        public static string MessageBoxAccountTypeEditSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAccountTypeEditSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAccountTypeEditSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAccountTypeEditSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding account type, please retry.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add &quot;{0}&quot; as a new account type ?.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeQuestionMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeQuestionNoButton {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeQuestionNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account type ?.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeQuestionTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeQuestionYesButton {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeQuestionYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new account type has been successfully added.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeSuccessOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeSuccessOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAddNewAccountTypeSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddNewAccountTypeSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteAccountTypeNoUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountTypeNoUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account type is in use.Are you sure you want to delete this account type and everything linked to it ?.
        /// </summary>
        public static string MessageBoxDeleteAccountTypeUseQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountTypeUseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type and all relative element was successfully removed.
        /// </summary>
        public static string MessageBoxDeleteAccountTypeUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAccountTypeUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this account type ?.
        /// </summary>
        public static string MessageBoxDeleteQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type already exist.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorAlreadyExistOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorAlreadyExistTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type can&apos;t be empty.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorEmptyMessage {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorEmptyOkButton {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxValidateAccountTypeErrorEmptyTitle {
            get {
                return ResourceManager.GetString("MessageBoxValidateAccountTypeErrorEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account type :.
        /// </summary>
        public static string TextBoxAccountTypeName {
            get {
                return ResourceManager.GetString("TextBoxAccountTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Change account type.
        /// </summary>
        public static string TitleWindow {
            get {
                return ResourceManager.GetString("TitleWindow", resourceCulture);
            }
        }
    }
}
