//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Pages.DashBoardPage {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashBoardPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashBoardPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Pages.DashBoardPage.DashBoardPageResources", typeof(DashBoardPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account management.
        /// </summary>
        internal static string ButtonAccountManagement {
            get {
                return ResourceManager.GetString("ButtonAccountManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account type management.
        /// </summary>
        internal static string ButtonAccountTypeManagement {
            get {
                return ResourceManager.GetString("ButtonAccountTypeManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category type management.
        /// </summary>
        internal static string ButtonCategoryTypeManagement {
            get {
                return ResourceManager.GetString("ButtonCategoryTypeManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color management.
        /// </summary>
        internal static string ButtonColorManagement {
            get {
                return ResourceManager.GetString("ButtonColorManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency symbols management.
        /// </summary>
        internal static string ButtonCurrencyManagement {
            get {
                return ResourceManager.GetString("ButtonCurrencyManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location management.
        /// </summary>
        internal static string ButtonLocationManagement {
            get {
                return ResourceManager.GetString("ButtonLocationManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make a bank transfer.
        /// </summary>
        internal static string ButtonMakeBankTransfer {
            get {
                return ResourceManager.GetString("ButtonMakeBankTransfer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode payment management.
        /// </summary>
        internal static string ButtonModePaymentManagement {
            get {
                return ResourceManager.GetString("ButtonModePaymentManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record an expense.
        /// </summary>
        internal static string ButtonRecordExpense {
            get {
                return ResourceManager.GetString("ButtonRecordExpense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string DataGridTextColumnAccount {
            get {
                return ResourceManager.GetString("DataGridTextColumnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DataGridTextColumnCategory {
            get {
                return ResourceManager.GetString("DataGridTextColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DataGridTextColumnDate {
            get {
                return ResourceManager.GetString("DataGridTextColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DataGridTextColumnDescription {
            get {
                return ResourceManager.GetString("DataGridTextColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode payment.
        /// </summary>
        internal static string DataGridTextColumnModePayment {
            get {
                return ResourceManager.GetString("DataGridTextColumnModePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointed.
        /// </summary>
        internal static string DataGridTextColumnPointed {
            get {
                return ResourceManager.GetString("DataGridTextColumnPointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DataGridTextColumnValue {
            get {
                return ResourceManager.GetString("DataGridTextColumnValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string DataGridTextColumnPlace {
            get {
                return ResourceManager.GetString("DataGridTextColumnPlace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit this record.
        /// </summary>
        internal static string DataGridMenuItemHeaderEditRecord {
            get {
                return ResourceManager.GetString("DataGridMenuItemHeaderEditRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit this record.
        /// </summary>
        internal static string DataGridMenuItemHeaderDeleteRecord {
            get {
                return ResourceManager.GetString("DataGridMenuItemHeaderDeleteRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choice of the year:.
        /// </summary>
        internal static string ComboBoxYearsHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxYearsHintAssist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choice of the month:.
        /// </summary>
        internal static string ComboBoxMonthHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxMonthHintAssist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graphical analyzes.
        /// </summary>
        internal static string ButtonAnalytics {
            get {
                return ResourceManager.GetString("ButtonAnalytics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No additional dates are available.
        /// </summary>
        internal static string MessageBoxAddMonthError {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No lower dates are available.
        /// </summary>
        internal static string MessageBoxRemoveMonthError {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonContentEditRecord {
            get {
                return ResourceManager.GetString("ButtonContentEditRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static object DataGridTemplateColumnActionsHeader {
            get {
                return ResourceManager.GetString("DataGridTemplateColumnActionsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this recording ?.
        /// </summary>
        internal static string MessageBoxDeleteRecordQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteRecordQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonContentDeleteRecord {
            get {
                return ResourceManager.GetString("ButtonContentDeleteRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm.
        /// </summary>
        internal static string FilterDataGridDateFormatString {
            get {
                return ResourceManager.GetString("FilterDataGridDateFormatString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Management of recurring expenses.
        /// </summary>
        internal static string ButtonRecurrentExpense {
            get {
                return ResourceManager.GetString("ButtonRecurrentExpense", resourceCulture);
            }
        }
    }
}
