//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Wpf.Resources.Resx.Converters.CallBackLaterTimeToStringConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CallBackLaterTimeToStringConverterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallBackLaterTimeToStringConverterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Wpf.Resources.Resx.Converters.CallBackLaterTimeToStringConverter.CallB" +
                            "ackLaterTimeToStringConverterResources", typeof(CallBackLaterTimeToStringConverterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 10 days.
        /// </summary>
        internal static string After10Days {
            get {
                return ResourceManager.GetString("After10Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 12 hours.
        /// </summary>
        internal static string After12Hours {
            get {
                return ResourceManager.GetString("After12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 1 days.
        /// </summary>
        internal static string After1Days {
            get {
                return ResourceManager.GetString("After1Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 2 days.
        /// </summary>
        internal static string After2Days {
            get {
                return ResourceManager.GetString("After2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 30 minutes.
        /// </summary>
        internal static string After30Minutes {
            get {
                return ResourceManager.GetString("After30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 4 days.
        /// </summary>
        internal static string After4Days {
            get {
                return ResourceManager.GetString("After4Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 8 days.
        /// </summary>
        internal static string After8Days {
            get {
                return ResourceManager.GetString("After8Days", resourceCulture);
            }
        }
    }
}
