//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Presentation.Resources.Resx.LocationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Presentation.Resources.Resx.LocationResources.LocationResources", typeof(LocationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new location.
        /// </summary>
        public static string AddLocationWindowTitle {
            get {
                return ResourceManager.GetString("AddLocationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        public static string ComboBoxBaseMapHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBaseMapHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a location.
        /// </summary>
        public static string EditLocationWindowTitle {
            get {
                return ResourceManager.GetString("EditLocationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new place.
        /// </summary>
        public static string MenuItemHeaderAddPoint {
            get {
                return ResourceManager.GetString("MenuItemHeaderAddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete place.
        /// </summary>
        public static string MenuItemHeaderDeleteFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderDeleteFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit point.
        /// </summary>
        public static string MenuItemHeaderEditFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderEditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Earth.
        /// </summary>
        public static string MenuItemHeaderGoogleEarthWeb {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleEarthWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Maps.
        /// </summary>
        public static string MenuItemHeaderGoogleMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Street View.
        /// </summary>
        public static string MenuItemHeaderGoogleStreetView {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleStreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MenuItemHeaderMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string PlaceCityHintAssist {
            get {
                return ResourceManager.GetString("PlaceCityHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string PlaceCountryHintAssist {
            get {
                return ResourceManager.GetString("PlaceCountryHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string PlaceNameHintAssist {
            get {
                return ResourceManager.GetString("PlaceNameHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Number.
        /// </summary>
        public static string PlaceNumberHintAssist {
            get {
                return ResourceManager.GetString("PlaceNumberHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PlacePostalHintAssist {
            get {
                return ResourceManager.GetString("PlacePostalHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string PlaceStreetHintAssist {
            get {
                return ResourceManager.GetString("PlaceStreetHintAssist", resourceCulture);
            }
        }
    }
}
