//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Presentation.Resources.Resx.LocationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Presentation.Resources.Resx.LocationResources.LocationResources", typeof(LocationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new location.
        /// </summary>
        public static string AddLocationWindowTitle {
            get {
                return ResourceManager.GetString("AddLocationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonContentCancel {
            get {
                return ResourceManager.GetString("ButtonContentCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonContentDelete {
            get {
                return ResourceManager.GetString("ButtonContentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by address.
        /// </summary>
        public static string ButtonContentSearchByAddress {
            get {
                return ResourceManager.GetString("ButtonContentSearchByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by contact information.
        /// </summary>
        public static string ButtonContentSearchByCoordinate {
            get {
                return ResourceManager.GetString("ButtonContentSearchByCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ButtonContentValid {
            get {
                return ResourceManager.GetString("ButtonContentValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate the new point.
        /// </summary>
        public static string ButtonContentValidNewPoint {
            get {
                return ResourceManager.GetString("ButtonContentValidNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in on the point.
        /// </summary>
        public static string ButtonContentZoomToPoint {
            get {
                return ResourceManager.GetString("ButtonContentZoomToPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place is open :.
        /// </summary>
        public static string CheckBoxContentIsOpen {
            get {
                return ResourceManager.GetString("CheckBoxContentIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        public static string ComboBoxBaseMapHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBaseMapHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a location.
        /// </summary>
        public static string EditLocationWindowTitle {
            get {
                return ResourceManager.GetString("EditLocationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new place.
        /// </summary>
        public static string MenuItemHeaderAddPoint {
            get {
                return ResourceManager.GetString("MenuItemHeaderAddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete place.
        /// </summary>
        public static string MenuItemHeaderDeleteFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderDeleteFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit point.
        /// </summary>
        public static string MenuItemHeaderEditFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderEditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Earth.
        /// </summary>
        public static string MenuItemHeaderGoogleEarthWeb {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleEarthWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Maps.
        /// </summary>
        public static string MenuItemHeaderGoogleMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Street View.
        /// </summary>
        public static string MenuItemHeaderGoogleStreetView {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleStreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MenuItemHeaderMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxPlaceCreateErrorCaption {
            get {
                return ResourceManager.GetString("MessageboxPlaceCreateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the location. Please try again.
        /// </summary>
        public static string MessageboxPlaceCreateErrorContent {
            get {
                return ResourceManager.GetString("MessageboxPlaceCreateErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxPlaceDeleteErrorCaption {
            get {
                return ResourceManager.GetString("MessageboxPlaceDeleteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n error occurred while deleting the location. Please try again.
        /// </summary>
        public static string MessageboxPlaceDeleteErrorContent {
            get {
                return ResourceManager.GetString("MessageboxPlaceDeleteErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxPlaceUpdateErrorCaption {
            get {
                return ResourceManager.GetString("MessageboxPlaceUpdateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the location. Please try again.
        /// </summary>
        public static string MessageboxPlaceUpdateErrorContent {
            get {
                return ResourceManager.GetString("MessageboxPlaceUpdateErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NominatimButtonCancel {
            get {
                return ResourceManager.GetString("NominatimButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string NominatimButtonValid {
            get {
                return ResourceManager.GetString("NominatimButtonValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location found!.
        /// </summary>
        public static string NominatimServiceSearchErrorAnyValueContent {
            get {
                return ResourceManager.GetString("NominatimServiceSearchErrorAnyValueContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string NominatimServiceSearchErrorAnyValueTitle {
            get {
                return ResourceManager.GetString("NominatimServiceSearchErrorAnyValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string NominatimServiceSearchErrorContent {
            get {
                return ResourceManager.GetString("NominatimServiceSearchErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please try again, Error code:{0}.
        /// </summary>
        public static string NominatimServiceSearchErrorTitle {
            get {
                return ResourceManager.GetString("NominatimServiceSearchErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string PlaceCityHintAssist {
            get {
                return ResourceManager.GetString("PlaceCityHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string PlaceCountryHintAssist {
            get {
                return ResourceManager.GetString("PlaceCountryHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude :.
        /// </summary>
        public static string PlaceLatitudeHintAssist {
            get {
                return ResourceManager.GetString("PlaceLatitudeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude :.
        /// </summary>
        public static string PlaceLongitudeHintAssist {
            get {
                return ResourceManager.GetString("PlaceLongitudeHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string PlaceNameHintAssist {
            get {
                return ResourceManager.GetString("PlaceNameHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Number.
        /// </summary>
        public static string PlaceNumberHintAssist {
            get {
                return ResourceManager.GetString("PlaceNumberHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PlacePostalHintAssist {
            get {
                return ResourceManager.GetString("PlacePostalHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string PlaceStreetHintAssist {
            get {
                return ResourceManager.GetString("PlaceStreetHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the city must be between 1 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorCityLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorCityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the country must be between 1 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorCountryLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorCountryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required.
        /// </summary>
        public static string PlaceViewModelValidatorLatitudeNotNull {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorLatitudeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is required.
        /// </summary>
        public static string PlaceViewModelValidatorLongitudeNotNull {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorLongitudeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be between 1 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorNameLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the place must be filled in.
        /// </summary>
        public static string PlaceViewModelValidatorNameRequired {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street number must be between 0 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorNumberLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code must be between 1 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorPostalLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorPostalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street name should be between 1 and {0} characters.
        /// </summary>
        public static string PlaceViewModelValidatorStreetLength {
            get {
                return ResourceManager.GetString("PlaceViewModelValidatorStreetLength", resourceCulture);
            }
        }
    }
}
