GET https://nominatim.openstreetmap.org/reverse?format=json&lat=44.880798852908725&lon=-0.566306328774544

### Effeil tower france
GET https://nominatim.openstreetmap.org/search?q=tour+eiffel&format=jsonv2&polygon_geojson=1