//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.SharedUtils.Resources.Resx.LocationManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationManagementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public LocationManagementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.SharedUtils.Resources.Resx.LocationManagement.LocationManagementResour" +
                            "ces", typeof(LocationManagementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap :.
        /// </summary>
        public static string ComboBoxBasemapHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxBasemapHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new point.
        /// </summary>
        public static string MenuItemHeaderAddPoint {
            get {
                return ResourceManager.GetString("MenuItemHeaderAddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete point.
        /// </summary>
        public static string MenuItemHeaderDeleteFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderDeleteFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit point.
        /// </summary>
        public static string MenuItemHeaderEditFeature {
            get {
                return ResourceManager.GetString("MenuItemHeaderEditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Earth web.
        /// </summary>
        public static string MenuItemHeaderGoogleEarthWeb {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleEarthWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Maps.
        /// </summary>
        public static string MenuItemHeaderGoogleMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Google Street View.
        /// </summary>
        public static string MenuItemHeaderGoogleStreetView {
            get {
                return ResourceManager.GetString("MenuItemHeaderGoogleStreetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MenuItemHeaderMaps {
            get {
                return ResourceManager.GetString("MenuItemHeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete place &quot;{0}&quot; ?.
        /// </summary>
        public static string MessageBoxDeleteQuestion {
            get {
                return ResourceManager.GetString("MessageBoxDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxEditPlaceErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditPlaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place was successfully edited.
        /// </summary>
        public static string MessageBoxEditPlaceSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxEditPlaceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxMenuItemDeleteFeatureError {
            get {
                return ResourceManager.GetString("MessageBoxMenuItemDeleteFeatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place was successfully removed.
        /// </summary>
        public static string MessageBoxMenuItemDeleteFeatureNoUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxMenuItemDeleteFeatureNoUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This location is in use.Are you sure you want to delete this location and everything linked to it ?.
        /// </summary>
        public static string MessageBoxMenuItemDeleteFeatureUseQuestion {
            get {
                return ResourceManager.GetString("MessageBoxMenuItemDeleteFeatureUseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place and all relative element was successfully removed.
        /// </summary>
        public static string MessageBoxMenuItemDeleteFeatureUseSuccess {
            get {
                return ResourceManager.GetString("MessageBoxMenuItemDeleteFeatureUseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This place cannot be changed or deleted.
        /// </summary>
        public static string MessageBoxPlaceCantEditMessage {
            get {
                return ResourceManager.GetString("MessageBoxPlaceCantEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new place has been added successfully.
        /// </summary>
        public static string MessageBoxProcessNewPlaceAddSuccess {
            get {
                return ResourceManager.GetString("MessageBoxProcessNewPlaceAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new location has been successfully edited.
        /// </summary>
        public static string MessageBoxProcessNewPlaceEditSuccess {
            get {
                return ResourceManager.GetString("MessageBoxProcessNewPlaceEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxProcessNewPlaceError {
            get {
                return ResourceManager.GetString("MessageBoxProcessNewPlaceError", resourceCulture);
            }
        }
    }
}
