//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Smartphones.Resources.Resx.ContentPages.DashBoardContentPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashBoardContentPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashBoardContentPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Smartphones.Resources.Resx.ContentPages.DashBoardContentPage.DashBoard" +
                            "ContentPageResources", typeof(DashBoardContentPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of the month :.
        /// </summary>
        internal static string ComboBoxMonthHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxMonthHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of the year :.
        /// </summary>
        internal static string ComboBoxYearsHintAssist {
            get {
                return ResourceManager.GetString("ComboBoxYearsHintAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional dates are available.
        /// </summary>
        internal static string MessageBoxAddMonthErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxAddMonthErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxAddMonthErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxAddMonthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressCheck {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to {0} this record ?{1}.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressMessage {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressNoButton {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm update of this record.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressTitle {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpoint.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressUnCheck {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressUnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MessageBoxCollectionViewVHistoryOnLongPressYesButton {
            get {
                return ResourceManager.GetString("MessageBoxCollectionViewVHistoryOnLongPressYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lower dates are available.
        /// </summary>
        internal static string MessageBoxRemoveMonthErrorMessage {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MessageBoxRemoveMonthErrorOkButton {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxRemoveMonthErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxRemoveMonthErrorTitle", resourceCulture);
            }
        }
    }
}
