name: WinGet submission on release
# based off of https://github.com/nushell/nushell/blob/main/.github/workflows/winget-submission.yml

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit TheR7angelo.MyExpenses package to Windows Package Manager Community Repository
        run: |

          $wingetPackage = "TheR7angelo.MyExpenses"
          $gitToken = "${{ secrets.GITHUB_TOKEN }}"

          $github = Invoke-RestMethod -uri "https://api.github.com/repos/TheR7angelo/MyExpenses/releases" 

          $targetRelease = $github | Where-Object { -not $_.draft -and -not $_.prerelease } | Select -First 1
          $installerUserX64Url = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'MyExpenses.*x64' | Select -ExpandProperty browser_download_url
          # $installerMachineX64Url = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'PowerToysSetup.*x64' | Select -ExpandProperty browser_download_url
          # $installerUserArmUrl = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'PowerToysUserSetup.*arm64' | Select -ExpandProperty browser_download_url
          # $installerMachineArmUrl = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'PowerToysSetup.*arm64' | Select -ExpandProperty browser_download_url
          $ver = $targetRelease.tag_name -ireplace '^v'

          # getting latest wingetcreate file
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          # .\wingetcreate.exe update $wingetPackage -s -v $ver -u "$installerUserX64Url|user" "$installerMachineX64Url|machine" "$installerUserArmUrl|user" "$installerMachineArmUrl|machine" -t $gitToken
          .\wingetcreate.exe update $wingetPackage -s -v $ver -u "$installerUserX64Url|user" -t $gitToken
