//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExpenses.Presentation.Resources.Resx.AccountResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyExpenses.Presentation.Resources.Resx.AccountResources.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type name must be unique.
        /// </summary>
        public static string AccountTypeViewModelValidatorNameAlreadyExists {
            get {
                return ResourceManager.GetString("AccountTypeViewModelValidatorNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type name is required.
        /// </summary>
        public static string AccountTypeViewModelValidatorNameRequired {
            get {
                return ResourceManager.GetString("AccountTypeViewModelValidatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 1 and {0} characters long.
        /// </summary>
        public static string AccountTypeViewModelValidatorNameTooLong {
            get {
                return ResourceManager.GetString("AccountTypeViewModelValidatorNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type is required.
        /// </summary>
        public static string AccountViewModelValidatorAccountTypeRequired {
            get {
                return ResourceManager.GetString("AccountViewModelValidatorAccountTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency type is required.
        /// </summary>
        public static string AccountViewModelValidatorCurrencyRequired {
            get {
                return ResourceManager.GetString("AccountViewModelValidatorCurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is required.
        /// </summary>
        public static string AccountViewModelValidatorNameRequired {
            get {
                return ResourceManager.GetString("AccountViewModelValidatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 1 and {0} characters long.
        /// </summary>
        public static string AccountViewModelValidatorNameTooLong {
            get {
                return ResourceManager.GetString("AccountViewModelValidatorNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency symbol must be unique.
        /// </summary>
        public static string CurrencyViewModelNameAlreadyExists {
            get {
                return ResourceManager.GetString("CurrencyViewModelNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A currency symbol is required.
        /// </summary>
        public static string CurrencyViewModelNameRequired {
            get {
                return ResourceManager.GetString("CurrencyViewModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol must be between 1 and {0} characters long.
        /// </summary>
        public static string CurrencyViewModelNameTooLong {
            get {
                return ResourceManager.GetString("CurrencyViewModelNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxAddEditAccountTypeErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxAddEditAccountTypeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxAddEditAccountTypeErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxAddEditAccountTypeErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxAddEditAccountTypeSuccessCaption {
            get {
                return ResourceManager.GetString("MessageBoxAddEditAccountTypeSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new account has been successfully added.
        /// </summary>
        public static string MessageBoxAddEditAccountTypeSuccessContent {
            get {
                return ResourceManager.GetString("MessageBoxAddEditAccountTypeSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCreateItemErrorAlreadyUsedCaption {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemErrorAlreadyUsedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is already in use, please enter a new one.
        /// </summary>
        public static string MessageBoxCreateItemErrorAlreadyUsedContent {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemErrorAlreadyUsedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCreateItemErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new &quot;{0}&quot; item. Please try again..
        /// </summary>
        public static string MessageBoxCreateItemErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MessageBoxCreateItemQuestionCaption {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create &quot;{0}&quot; ?.
        /// </summary>
        public static string MessageBoxCreateItemQuestionContent {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxCreateItemSuccessCaption {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; element has been successfully created.
        /// </summary>
        public static string MessageBoxCreateItemSuccessContent {
            get {
                return ResourceManager.GetString("MessageBoxCreateItemSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxDeleteItemQuestionCaption {
            get {
                return ResourceManager.GetString("MessageBoxDeleteItemQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot; ?.
        /// </summary>
        public static string MessageBoxDeleteItemQuestionContent {
            get {
                return ResourceManager.GetString("MessageBoxDeleteItemQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxDeleteItemSuccessCaption {
            get {
                return ResourceManager.GetString("MessageBoxDeleteItemSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &quot;{0}&quot; has been successfully deleted.
        /// </summary>
        public static string MessageBoxDeleteItemSuccessContent {
            get {
                return ResourceManager.GetString("MessageBoxDeleteItemSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxDeleteteErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxDeleteteErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxDeletetemErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxDeletetemErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxEditItemErrorAlreadyUsedCaption {
            get {
                return ResourceManager.GetString("MessageBoxEditItemErrorAlreadyUsedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is already in use, please enter a new one.
        /// </summary>
        public static string MessageBoxEditItemErrorAlreadyUsedContent {
            get {
                return ResourceManager.GetString("MessageBoxEditItemErrorAlreadyUsedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxEditItemErrorCaption {
            get {
                return ResourceManager.GetString("MessageBoxEditItemErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please retry.
        /// </summary>
        public static string MessageBoxEditItemErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxEditItemErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MessageBoxEditItemQuestionCaption {
            get {
                return ResourceManager.GetString("MessageBoxEditItemQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to rename &quot;{0}&quot; to &quot;{1}&quot; ?.
        /// </summary>
        public static string MessageBoxEditItemQuestionContent {
            get {
                return ResourceManager.GetString("MessageBoxEditItemQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current changes are pending, do you really want to update them ?{0}{1}.
        /// </summary>
        public static string MessageBoxEditItemsQuestionContent {
            get {
                return ResourceManager.GetString("MessageBoxEditItemsQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxEditItemSuccessCaption {
            get {
                return ResourceManager.GetString("MessageBoxEditItemSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been successfully modified.
        /// </summary>
        public static string MessageBoxEditItemSuccessContent {
            get {
                return ResourceManager.GetString("MessageBoxEditItemSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading accounts.
        /// </summary>
        public static string MessageBoxLoadAccountErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxLoadAccountErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading account types.
        /// </summary>
        public static string MessageBoxLoadAccountTypeErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxLoadAccountTypeErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxUpdateAccountSuccessCaption {
            get {
                return ResourceManager.GetString("MessageBoxUpdateAccountSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been successfully modified.
        /// </summary>
        public static string MessageBoxUpdateAccountSuccessMessage {
            get {
                return ResourceManager.GetString("MessageBoxUpdateAccountSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while viewing account.
        /// </summary>
        public static string MessageBoxViewAccountErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxViewAccountErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while viewing account type.
        /// </summary>
        public static string MessageBoxViewAccountTypeErrorContent {
            get {
                return ResourceManager.GetString("MessageBoxViewAccountTypeErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account type name :.
        /// </summary>
        public static string TextBoxAddNewAccountTypeName {
            get {
                return ResourceManager.GetString("TextBoxAddNewAccountTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new currency symbol :.
        /// </summary>
        public static string TextBoxAddNewCurrencySymbol {
            get {
                return ResourceManager.GetString("TextBoxAddNewCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account type name :.
        /// </summary>
        public static string TextBoxEditAccountTypeName {
            get {
                return ResourceManager.GetString("TextBoxEditAccountTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency symbol :.
        /// </summary>
        public static string TextBoxEditCurrencySymbol {
            get {
                return ResourceManager.GetString("TextBoxEditCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account type.
        /// </summary>
        public static string TitleWindowAddAccountTypeName {
            get {
                return ResourceManager.GetString("TitleWindowAddAccountTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new currency symbol.
        /// </summary>
        public static string TitleWindowAddCurrencySymbol {
            get {
                return ResourceManager.GetString("TitleWindowAddCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account type.
        /// </summary>
        public static string TitleWindowEditAccountTypeName {
            get {
                return ResourceManager.GetString("TitleWindowEditAccountTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency symbol.
        /// </summary>
        public static string TitleWindowEditCurrencySymbol {
            get {
                return ResourceManager.GetString("TitleWindowEditCurrencySymbol", resourceCulture);
            }
        }
    }
}
